Update regression-report.yml

diff --git a/.github/workflows/regression-report.yml b/.github/workflows/regression-report.yml
--- a/.github/workflows/regression-report.yml
+++ b/.github/workflows/regression-report.yml
@@ -146,72 +146,72 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      # - name: Generate report
-      #   env:
-      #     BRANCH: ${{ needs.parse_comment.outputs.branch }}
-      #   run: |
-      #     # Start from the repository root
-      #     cd $GITHUB_WORKSPACE
-          
-      #     # Ensure we have the latest branches
-      #     git fetch --all --prune
-          
-      #     # Set variables
-      #     REF="origin/$BRANCH"
-      #     REPO="$GITHUB_WORKSPACE"
-      #     BASE_BRANCH="upstream/master"
-          
-      #     # Verify the branch exists
-      #     if ! git rev-parse --verify "$REF" >/dev/null 2>&1; then
-      #       echo "Error: Branch $REF does not exist!"
-      #       git branch -a  # List all branches for debugging
-      #       exit 1
-      #     fi
-          
-      #     # Change to the checkstyle-tester directory
-      #     cd .ci-temp/contribution/checkstyle-tester
-          
-      #     # Set Maven options
-      #     export MAVEN_OPTS="-Xmx5g"
-          
-      #     # Run the appropriate Groovy command
-      #     if [ -f new_module_config.xml ]; then
-      #       groovy diff.groovy -r "$REPO" -p "$REF" -pc new_module_config.xml -m single \
-      #         -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
-      #         --allowExcludes
-      #     elif [ -f patch_config.xml ]; then
-      #       groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -bc diff_config.xml \
-      #         -pc patch_config.xml -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
-      #         --allowExcludes
-      #     else
-      #       groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -c diff_config.xml \
-      #         -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
-      #         --allowExcludes
-      #     fi
-
       - name: Generate report
         env:
-          BRANCH: ${{ needs.parse_body.outputs.branch }}
+          BRANCH: ${{ needs.parse_comment.outputs.branch }}
         run: |
-          cd .ci-temp/contribution/checkstyle-tester
-          bash
+          # Start from the repository root
+          cd $GITHUB_WORKSPACE
+          
+          # Ensure we have the latest branches
+          git fetch --all --prune
+          
+          # Set variables
           REF="forked/$BRANCH"
-          REPO="../../../../checkstyle"
+          REPO="$GITHUB_WORKSPACE"
           BASE_BRANCH="upstream/master"
+          
+          # Verify the branch exists
+          if ! git rev-parse --verify "$REF" >/dev/null 2>&1; then
+            echo "Error: Branch $REF does not exist!"
+            git branch -a  # List all branches for debugging
+            exit 1
+          fi
+          
+          # Change to the checkstyle-tester directory
+          cd .ci-temp/contribution/checkstyle-tester
+          
+          # Set Maven options
           export MAVEN_OPTS="-Xmx5g"
+          
+          # Run the appropriate Groovy command
           if [ -f new_module_config.xml ]; then
-            groovy diff.groovy -r "$REPO" -p "$REF" -pc new_module_config.xml -m single\
-              -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+            groovy diff.groovy -r "$REPO" -p "$REF" -pc new_module_config.xml -m single \
+              -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes
           elif [ -f patch_config.xml ]; then
-            groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -bc diff_config.xml\
-              -pc patch_config.xml -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+            groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -bc diff_config.xml \
+              -pc patch_config.xml -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes
           else
-            groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -c diff_config.xml\
-              -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+            groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -c diff_config.xml \
+              -l project.properties -xm "-Dcheckstyle.failsOnError=false" \
               --allowExcludes
           fi
+
+      # - name: Generate report
+      #   env:
+      #     BRANCH: ${{ needs.parse_body.outputs.branch }}
+      #   run: |
+      #     cd .ci-temp/contribution/checkstyle-tester
+      #     bash
+      #     REF="forked/$BRANCH"
+      #     REPO="../../../../checkstyle"
+      #     BASE_BRANCH="upstream/master"
+      #     export MAVEN_OPTS="-Xmx5g"
+      #     if [ -f new_module_config.xml ]; then
+      #       groovy diff.groovy -r "$REPO" -p "$REF" -pc new_module_config.xml -m single\
+      #         -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+      #         --allowExcludes
+      #     elif [ -f patch_config.xml ]; then
+      #       groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -bc diff_config.xml\
+      #         -pc patch_config.xml -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+      #         --allowExcludes
+      #     else
+      #       groovy diff.groovy -r "$REPO" -b "$BASE_BRANCH" -p "$REF" -c diff_config.xml\
+      #         -l project.properties -xm "-Dcheckstyle.failsOnError=false"\
+      #         --allowExcludes
+      #     fi
           
       - name: Copy Report to AWS S3 Bucket
         run: |
